namespace spritePackSprites {
    //% fixedInstance jres blockIdentity=images._image
    export const tile01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile09 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tile32 = image.ofBuffer(hex``);

}
